<?php
$_errLang  = $_COOKIE['jj_lang']  ?? 'en';
$_errTheme = $_COOKIE['jj_theme'] ?? 'dark';
$_validL   = ['en','de','nl','sv','no','da','fr','es','pt','it','cs','sk','pl','ru','uk','tr','id','ja','ko','hu'];
if (!in_array($_errLang, $_validL, true)) $_errLang = 'en';

$_errI18n = [
    'en' => [
        '400.title' => 'Bad Request',
        '400.desc'  => 'The server could not understand the request.',
        '403.title' => 'Access Forbidden',
        '403.desc'  => 'You do not have permission to access this page.',
        '404.title' => 'Page Not Found',
        '404.desc'  => 'The page you are looking for does not exist or has been moved.',
        '500.title' => 'Internal Server Error',
        '500.desc'  => 'Something went wrong on the server. Please try again later.',
        'db.title'  => 'Database Connection Error',
        'db.desc'   => 'The application cannot connect to the database. Please check the configuration.',
        'php.title' => 'Application Error',
        'php.desc'  => 'A PHP error has occurred. Please check the server logs.',
        'btn.home'   => 'Home', 'btn.login' => 'Login',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Open Config',
    ],
    'cs' => [
        '400.title' => 'Špatný požadavek',
        '400.desc'  => 'Server nemohl porozumět požadavku.',
        '403.title' => 'Přístup zamítnut',
        '403.desc'  => 'Nemáte oprávnění k přístupu na tuto stránku.',
        '404.title' => 'Stránka nenalezena',
        '404.desc'  => 'Hledaná stránka neexistuje nebo byla přesunuta.',
        '500.title' => 'Interní chyba serveru',
        '500.desc'  => 'Na serveru se něco pokazilo. Zkuste to prosím znovu.',
        'db.title'  => 'Chyba připojení k databázi',
        'db.desc'   => 'Aplikace se nemůže připojit k databázi. Zkontrolujte konfiguraci.',
        'php.title' => 'Chyba aplikace',
        'php.desc'  => 'Vyskytla se chyba PHP. Zkontrolujte protokoly serveru.',
        'btn.home'   => 'Domů', 'btn.login' => 'Přihlásit',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Otevřít konfiguraci',
    ],
    'de' => [
        '400.title' => 'Ungültige Anfrage',
        '400.desc'  => 'Der Server konnte die Anfrage nicht verarbeiten.',
        '403.title' => 'Zugriff verweigert',
        '403.desc'  => 'Sie haben keine Berechtigung für diese Seite.',
        '404.title' => 'Seite nicht gefunden',
        '404.desc'  => 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
        '500.title' => 'Interner Serverfehler',
        '500.desc'  => 'Auf dem Server ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.',
        'db.title'  => 'Datenbankverbindungsfehler',
        'db.desc'   => 'Die Anwendung kann keine Verbindung zur Datenbank herstellen.',
        'php.title' => 'Anwendungsfehler',
        'php.desc'  => 'Ein PHP-Fehler ist aufgetreten. Bitte prüfen Sie die Serverprotokolle.',
        'btn.home'   => 'Startseite', 'btn.login' => 'Anmelden',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Konfiguration öffnen',
    ],
    'fr' => [
        '400.title' => 'Mauvaise requête',
        '400.desc'  => 'Le serveur n\'a pas pu comprendre la requête.',
        '403.title' => 'Accès interdit',
        '403.desc'  => 'Vous n\'avez pas la permission d\'accéder à cette page.',
        '404.title' => 'Page introuvable',
        '404.desc'  => 'La page que vous recherchez n\'existe pas ou a été déplacée.',
        '500.title' => 'Erreur interne du serveur',
        '500.desc'  => 'Une erreur s\'est produite sur le serveur. Veuillez réessayer plus tard.',
        'db.title'  => 'Erreur de connexion à la base de données',
        'db.desc'   => 'L\'application ne peut pas se connecter à la base de données.',
        'php.title' => 'Erreur d\'application',
        'php.desc'  => 'Une erreur PHP s\'est produite. Consultez les journaux du serveur.',
        'btn.home'   => 'Accueil', 'btn.login' => 'Connexion',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Ouvrir la configuration',
    ],
    'es' => [
        '400.title' => 'Solicitud incorrecta',
        '400.desc'  => 'El servidor no pudo entender la solicitud.',
        '403.title' => 'Acceso prohibido',
        '403.desc'  => 'No tienes permiso para acceder a esta página.',
        '404.title' => 'Página no encontrada',
        '404.desc'  => 'La página que buscas no existe o ha sido movida.',
        '500.title' => 'Error interno del servidor',
        '500.desc'  => 'Algo salió mal en el servidor. Inténtalo de nuevo más tarde.',
        'db.title'  => 'Error de conexión a la base de datos',
        'db.desc'   => 'La aplicación no puede conectarse a la base de datos.',
        'php.title' => 'Error de aplicación',
        'php.desc'  => 'Se ha producido un error PHP. Consulte los registros del servidor.',
        'btn.home'   => 'Inicio', 'btn.login' => 'Iniciar sesión',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Abrir configuración',
    ],
    'pt' => [
        '400.title' => 'Pedido inválido',
        '400.desc'  => 'O servidor não conseguiu entender a solicitação.',
        '403.title' => 'Acesso proibido',
        '403.desc'  => 'Você não tem permissão para acessar esta página.',
        '404.title' => 'Página não encontrada',
        '404.desc'  => 'A página que você procura não existe ou foi movida.',
        '500.title' => 'Erro interno do servidor',
        '500.desc'  => 'Algo deu errado no servidor. Tente novamente mais tarde.',
        'db.title'  => 'Erro de conexão com o banco de dados',
        'db.desc'   => 'A aplicação não consegue conectar ao banco de dados.',
        'php.title' => 'Erro de aplicação',
        'php.desc'  => 'Ocorreu um erro PHP. Verifique os registos do servidor.',
        'btn.home'   => 'Início', 'btn.login' => 'Entrar',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Abrir configuração',
    ],
    'it' => [
        '400.title' => 'Richiesta non valida',
        '400.desc'  => 'Il server non ha potuto elaborare la richiesta.',
        '403.title' => 'Accesso negato',
        '403.desc'  => 'Non hai il permesso di accedere a questa pagina.',
        '404.title' => 'Pagina non trovata',
        '404.desc'  => 'La pagina che stai cercando non esiste o è stata spostata.',
        '500.title' => 'Errore interno del server',
        '500.desc'  => 'Si è verificato un errore sul server. Riprova più tardi.',
        'db.title'  => 'Errore di connessione al database',
        'db.desc'   => 'L\'applicazione non riesce a connettersi al database.',
        'php.title' => 'Errore dell\'applicazione',
        'php.desc'  => 'Si è verificato un errore PHP. Controlla i log del server.',
        'btn.home'   => 'Home', 'btn.login' => 'Accedi',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Apri configurazione',
    ],
    'nl' => [
        '400.title' => 'Ongeldige aanvraag',
        '400.desc'  => 'De server kon het verzoek niet begrijpen.',
        '403.title' => 'Toegang verboden',
        '403.desc'  => 'U heeft geen toegang tot deze pagina.',
        '404.title' => 'Pagina niet gevonden',
        '404.desc'  => 'De pagina die u zoekt bestaat niet of is verplaatst.',
        '500.title' => 'Interne serverfout',
        '500.desc'  => 'Er is iets misgegaan op de server. Probeer het later opnieuw.',
        'db.title'  => 'Databaseverbindingsfout',
        'db.desc'   => 'De applicatie kan geen verbinding maken met de database.',
        'php.title' => 'Applicatiefout',
        'php.desc'  => 'Er is een PHP-fout opgetreden. Controleer de serverlogboeken.',
        'btn.home'   => 'Home', 'btn.login' => 'Inloggen',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Configuratie openen',
    ],
    'pl' => [
        '400.title' => 'Nieprawidłowe żądanie',
        '400.desc'  => 'Serwer nie mógł zrozumieć żądania.',
        '403.title' => 'Dostęp zabroniony',
        '403.desc'  => 'Nie masz uprawnień do tej strony.',
        '404.title' => 'Strona nie znaleziona',
        '404.desc'  => 'Szukana strona nie istnieje lub została przeniesiona.',
        '500.title' => 'Wewnętrzny błąd serwera',
        '500.desc'  => 'Coś poszło nie tak na serwerze. Spróbuj ponownie później.',
        'db.title'  => 'Błąd połączenia z bazą danych',
        'db.desc'   => 'Aplikacja nie może połączyć się z bazą danych.',
        'php.title' => 'Błąd aplikacji',
        'php.desc'  => 'Wystąpił błąd PHP. Sprawdź logi serwera.',
        'btn.home'   => 'Strona główna', 'btn.login' => 'Zaloguj',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Otwórz konfigurację',
    ],
    'sk' => [
        '400.title' => 'Neplatná požiadavka',
        '400.desc'  => 'Server nerozumel požiadavke.',
        '403.title' => 'Prístup zamietnutý',
        '403.desc'  => 'Nemáte oprávnenie na prístup k tejto stránke.',
        '404.title' => 'Stránka nenájdená',
        '404.desc'  => 'Hľadaná stránka neexistuje alebo bola presunutá.',
        '500.title' => 'Interná chyba servera',
        '500.desc'  => 'Na serveri sa niečo pokazilo. Skúste to neskôr.',
        'db.title'  => 'Chyba pripojenia k databáze',
        'db.desc'   => 'Aplikácia sa nemôže pripojiť k databáze.',
        'php.title' => 'Chyba aplikácie',
        'php.desc'  => 'Vyskytla sa chyba PHP. Skontrolujte protokoly servera.',
        'btn.home'   => 'Domov', 'btn.login' => 'Prihlásiť',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Otvoriť konfiguráciu',
    ],
    'sv' => [
        '400.title' => 'Ogiltig begäran',
        '400.desc'  => 'Servern kunde inte förstå begäran.',
        '403.title' => 'Åtkomst nekad',
        '403.desc'  => 'Du har inte behörighet att se den här sidan.',
        '404.title' => 'Sidan hittades inte',
        '404.desc'  => 'Sidan du söker finns inte eller har flyttats.',
        '500.title' => 'Internt serverfel',
        '500.desc'  => 'Något gick fel på servern. Försök igen senare.',
        'db.title'  => 'Databasanslutningsfel',
        'db.desc'   => 'Programmet kan inte ansluta till databasen.',
        'php.title' => 'Programfel',
        'php.desc'  => 'Ett PHP-fel har inträffat. Kontrollera serverloggarna.',
        'btn.home'   => 'Hem', 'btn.login' => 'Logga in',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Öppna konfiguration',
    ],
    'no' => [
        '400.title' => 'Ugyldig forespørsel',
        '400.desc'  => 'Serveren kunne ikke forstå forespørselen.',
        '403.title' => 'Tilgang nektet',
        '403.desc'  => 'Du har ikke tillatelse til å se denne siden.',
        '404.title' => 'Siden ble ikke funnet',
        '404.desc'  => 'Siden du leter etter eksisterer ikke eller er flyttet.',
        '500.title' => 'Intern serverfeil',
        '500.desc'  => 'Noe gikk galt på serveren. Prøv igjen senere.',
        'db.title'  => 'Databasetilkoblingsfeil',
        'db.desc'   => 'Programmet kan ikke koble til databasen.',
        'php.title' => 'Programfeil',
        'php.desc'  => 'En PHP-feil har oppstått. Sjekk serverloggene.',
        'btn.home'   => 'Hjem', 'btn.login' => 'Logg inn',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Åpne konfigurasjon',
    ],
    'da' => [
        '400.title' => 'Ugyldig anmodning',
        '400.desc'  => 'Serveren kunne ikke forstå anmodningen.',
        '403.title' => 'Adgang forbudt',
        '403.desc'  => 'Du har ikke tilladelse til at se denne side.',
        '404.title' => 'Siden blev ikke fundet',
        '404.desc'  => 'Siden du leder efter findes ikke eller er blevet flyttet.',
        '500.title' => 'Intern serverfejl',
        '500.desc'  => 'Noget gik galt på serveren. Prøv igen senere.',
        'db.title'  => 'Databaseforbindelsesfejl',
        'db.desc'   => 'Programmet kan ikke oprette forbindelse til databasen.',
        'php.title' => 'Programfejl',
        'php.desc'  => 'Der er opstået en PHP-fejl. Tjek serverloggene.',
        'btn.home'   => 'Hjem', 'btn.login' => 'Log ind',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Åbn konfiguration',
    ],
    'ru' => [
        '400.title' => 'Неверный запрос',
        '400.desc'  => 'Сервер не смог обработать запрос.',
        '403.title' => 'Доступ запрещён',
        '403.desc'  => 'У вас нет прав доступа к этой странице.',
        '404.title' => 'Страница не найдена',
        '404.desc'  => 'Страница не существует или была перемещена.',
        '500.title' => 'Внутренняя ошибка сервера',
        '500.desc'  => 'Что-то пошло не так. Пожалуйста, попробуйте позже.',
        'db.title'  => 'Ошибка подключения к базе данных',
        'db.desc'   => 'Приложение не может подключиться к базе данных.',
        'php.title' => 'Ошибка приложения',
        'php.desc'  => 'Произошла ошибка PHP. Проверьте журналы сервера.',
        'btn.home'   => 'Главная', 'btn.login' => 'Войти',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Открыть настройки',
    ],
    'uk' => [
        '400.title' => 'Невірний запит',
        '400.desc'  => 'Сервер не зміг обробити запит.',
        '403.title' => 'Доступ заборонено',
        '403.desc'  => 'У вас немає дозволу на доступ до цієї сторінки.',
        '404.title' => 'Сторінку не знайдено',
        '404.desc'  => 'Сторінка не існує або була переміщена.',
        '500.title' => 'Внутрішня помилка сервера',
        '500.desc'  => 'Щось пішло не так. Спробуйте пізніше.',
        'db.title'  => 'Помилка підключення до бази даних',
        'db.desc'   => 'Застосунок не може підключитися до бази даних.',
        'php.title' => 'Помилка застосунку',
        'php.desc'  => 'Виникла помилка PHP. Перевірте журнали сервера.',
        'btn.home'   => 'Головна', 'btn.login' => 'Увійти',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Відкрити налаштування',
    ],
    'tr' => [
        '400.title' => 'Hatalı İstek',
        '400.desc'  => 'Sunucu isteği anlayamadı.',
        '403.title' => 'Erişim Yasak',
        '403.desc'  => 'Bu sayfaya erişim izniniz yok.',
        '404.title' => 'Sayfa Bulunamadı',
        '404.desc'  => 'Aradığınız sayfa mevcut değil veya taşındı.',
        '500.title' => 'Sunucu Hatası',
        '500.desc'  => 'Sunucuda bir şeyler ters gitti. Lütfen daha sonra tekrar deneyin.',
        'db.title'  => 'Veritabanı Bağlantı Hatası',
        'db.desc'   => 'Uygulama veritabanına bağlanamıyor.',
        'php.title' => 'Uygulama Hatası',
        'php.desc'  => 'Bir PHP hatası oluştu. Sunucu günlüklerini kontrol edin.',
        'btn.home'   => 'Anasayfa', 'btn.login' => 'Giriş',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Yapılandırmayı aç',
    ],
    'id' => [
        '400.title' => 'Permintaan Tidak Valid',
        '400.desc'  => 'Server tidak dapat memahami permintaan.',
        '403.title' => 'Akses Ditolak',
        '403.desc'  => 'Anda tidak memiliki izin untuk mengakses halaman ini.',
        '404.title' => 'Halaman Tidak Ditemukan',
        '404.desc'  => 'Halaman yang Anda cari tidak ada atau telah dipindahkan.',
        '500.title' => 'Kesalahan Server Internal',
        '500.desc'  => 'Terjadi kesalahan pada server. Silakan coba lagi nanti.',
        'db.title'  => 'Kesalahan Koneksi Database',
        'db.desc'   => 'Aplikasi tidak dapat terhubung ke database.',
        'php.title' => 'Kesalahan Aplikasi',
        'php.desc'  => 'Terjadi kesalahan PHP. Periksa log server.',
        'btn.home'   => 'Beranda', 'btn.login' => 'Masuk',
        'btn.logbook'=> 'Logbook', 'btn.config' => 'Buka konfigurasi',
    ],
    'ja' => [
        '400.title' => '不正なリクエスト',
        '400.desc'  => 'サーバーがリクエストを理解できませんでした。',
        '403.title' => 'アクセス禁止',
        '403.desc'  => 'このページへのアクセス権がありません。',
        '404.title' => 'ページが見つかりません',
        '404.desc'  => 'お探しのページは存在しないか、移動されました。',
        '500.title' => '内部サーバーエラー',
        '500.desc'  => 'サーバーで問題が発生しました。後でもう一度お試しください。',
        'db.title'  => 'データベース接続エラー',
        'db.desc'   => 'アプリケーションがデータベースに接続できません。',
        'php.title' => 'アプリケーションエラー',
        'php.desc'  => 'PHPエラーが発生しました。サーバーログを確認してください。',
        'btn.home'   => 'ホーム', 'btn.login' => 'ログイン',
        'btn.logbook'=> 'Logbook', 'btn.config' => '設定を開く',
    ],
    'ko' => [
        '400.title' => '잘못된 요청',
        '400.desc'  => '서버가 요청을 이해할 수 없습니다.',
        '403.title' => '접근 금지',
        '403.desc'  => '이 페이지에 접근할 권한이 없습니다.',
        '404.title' => '페이지를 찾을 수 없음',
        '404.desc'  => '찾는 페이지가 없거나 이동되었습니다.',
        '500.title' => '내부 서버 오류',
        '500.desc'  => '서버에서 문제가 발생했습니다. 나중에 다시 시도하세요.',
        'db.title'  => '데이터베이스 연결 오류',
        'db.desc'   => '애플리케이션이 데이터베이스에 연결할 수 없습니다.',
        'php.title' => '애플리케이션 오류',
        'php.desc'  => 'PHP 오류가 발생했습니다. 서버 로그를 확인하세요.',
        'btn.home'   => '홈', 'btn.login' => '로그인',
        'btn.logbook'=> 'Logbook', 'btn.config' => '설정 열기',
    ],
    'hu' => [
        '400.title' => 'Hibás kérés',
        '400.desc'  => 'A szerver nem tudta értelmezni a kérést.',
        '403.title' => 'Hozzáférés megtagadva',
        '403.desc'  => 'Nincs jogosultsága az oldal megtekintéséhez.',
        '404.title' => 'Az oldal nem található',
        '404.desc'  => 'A keresett oldal nem létezik vagy át lett helyezve.',
        '500.title' => 'Belső szerverhiba',
        '500.desc'  => 'Valami hiba történt a szerveren. Kérjük, próbálja meg később.',
        'db.title'  => 'Adatbázis-kapcsolati hiba',
        'db.desc'   => 'Az alkalmazás nem tud csatlakozni az adatbázishoz. Ellenőrizze a beállításokat.',
        'php.title' => 'Alkalmazáshiba',
        'php.desc'  => 'PHP-hiba történt. Ellenőrizze a szerver naplókat.',
        'btn.home'   => 'Főoldal', 'btn.login' => 'Bejelentkezés',
        'btn.logbook'=> 'Naplókönyv', 'btn.config' => 'Konfiguráció megnyitása',
    ],
];

function _errT(string $key): string {
    global $_errLang, $_errI18n;
    $t = $_errI18n[$_errLang][$key] ?? $_errI18n['en'][$key] ?? $key;
    return htmlspecialchars($t, ENT_QUOTES, 'UTF-8');
}

$_errThemeEsc = htmlspecialchars($_errTheme, ENT_QUOTES, 'UTF-8');
$_errLangEsc  = htmlspecialchars($_errLang,  ENT_QUOTES, 'UTF-8');
?><!DOCTYPE html>
<html lang="<?= $_errLangEsc ?>" data-bs-theme="<?= $_errThemeEsc ?>" data-theme="<?= $_errThemeEsc ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= _errT($_errTitleKey) ?> | JOTA-JOTI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="d-flex align-items-center justify-content-center" style="min-height:100vh">
<div class="text-center p-4" style="max-width:520px">
    <?= $_errIconHtml ?? '' ?>
    <?php if (!empty($_errCode)): ?>
    <h1 class="display-1 fw-bold mb-0" style="color:<?= htmlspecialchars($_errCodeColor ?? 'var(--jj-accent)', ENT_QUOTES) ?>"><?= htmlspecialchars($_errCode, ENT_QUOTES) ?></h1>
    <?php endif; ?>
    <h2 class="text-gold mb-3 mt-2"><?= _errT($_errTitleKey) ?></h2>
    <p class="text-jj-muted mb-4"><?= _errT($_errDescKey) ?></p>
    <?php if (!empty($_errExtra)): ?>
    <?= $_errExtra ?>
    <?php endif; ?>
    <div class="d-flex flex-wrap gap-2 justify-content-center">
    <?php foreach (($_errButtons ?? []) as $btn): ?>
        <a href="<?= htmlspecialchars($btn['href'], ENT_QUOTES) ?>"
           class="btn <?= htmlspecialchars($btn['class'] ?? 'btn-jj-primary', ENT_QUOTES) ?>">
            <i class="fa-solid <?= htmlspecialchars($btn['icon'], ENT_QUOTES) ?> me-2"></i><?= _errT($btn['key']) ?>
        </a>
    <?php endforeach; ?>
    </div>
</div>
</body>
</html>
<?php exit; ?>
